default:
  refresh: TRUE
  push_dbs:
    load: ''
    proc: ''
    dedupe: ''
  routines:
    load: TRUE
    proc: TRUE
    dedupe: TRUE
  muni_ids: [274, 49, 35]
  most_recent: FALSE
  return_intermediate: FALSE
  company_count: 50000
  thresh:
    cosine: 0.85
    inds: 0.95
    zip_int: 1
  inds_thresh: 0.95
  zip_int_thresh: 1
  quiet: FALSE
  crs: 2249
  data_path: 'data'
  results_path: 'results'
  oc:
    path: '2024-04-12'
    companies: "companies.csv"
    officers: "officers.csv"
  gdb: 
    path: 'L3_AGGREGATE_FGDB_20240703'
    assess: 'L3_ASSESS'
    parcel: 'L3_TAXPAR_POLY'

complete:
  refresh: TRUE
  company_count: NULL
  muni_ids: NULL
  routines:
    load: TRUE
    proc: TRUE
    dedupe: TRUE